-- MYSQL_DELTA_PIPELINE_TERRITORY_ADMIN_3D.sql

SET NAMES utf8mb4;

-- PIPELINE RELAZIONI (grafo rete)
CREATE TABLE IF NOT EXISTS pipeline_relations (
  id            BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  upline_id     BIGINT UNSIGNED NOT NULL COMMENT 'chi ha invitato',
  downline_id   BIGINT UNSIGNED NOT NULL UNIQUE COMMENT 'chi è stato invitato',
  profondita    TINYINT UNSIGNED NOT NULL DEFAULT 1,
  created_at    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (upline_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (downline_id) REFERENCES users(id) ON DELETE CASCADE,
  INDEX idx_upline (upline_id),
  INDEX idx_downline (downline_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- TERRITORY MAP
CREATE TABLE IF NOT EXISTS territory_areas (
  id            BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  tipo          ENUM('REGIONE','PROVINCIA','COMUNE') NOT NULL,
  nome          VARCHAR(100) NOT NULL,
  codice        VARCHAR(20) NOT NULL COMMENT 'codice ISTAT o sigla',
  regione_ref   VARCHAR(50) NULL,
  provincia_ref VARCHAR(50) NULL,
  status        ENUM('LIBERA','RISERVATA','ASSEGNATA','SOSPESA') NOT NULL DEFAULT 'LIBERA',
  titolare_id   BIGINT UNSIGNED NULL COMMENT 'ELITE81+ assegnatario',
  point81_attivo TINYINT(1) NOT NULL DEFAULT 0,
  note          TEXT NULL,
  created_at    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (titolare_id) REFERENCES users(id) ON DELETE SET NULL,
  INDEX idx_tipo_status (tipo, status),
  INDEX idx_codice (codice)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- CLUB81+
CREATE TABLE IF NOT EXISTS club81_membership (
  id            BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id       BIGINT UNSIGNED NOT NULL UNIQUE,
  livello       ENUM('PALLADIUM','IRIDIUM','RHODIUM','OSMIUM','RHENIUM') NOT NULL,
  status        ENUM('ACTIVE','INACTIVE','PENDING') NOT NULL DEFAULT 'PENDING',
  pv_mensili_richiesti DECIMAL(18,4) NOT NULL,
  attivo_dal    DATE NULL,
  scade_il      DATE NULL,
  created_at    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- FRANCHISING / POINT81+
CREATE TABLE IF NOT EXISTS franchising_applications (
  id            BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id       BIGINT UNSIGNED NOT NULL,
  tipo          ENUM('SATELLITE81+','STATION81+','COMMAND81+','SEDE_PROVINCIALE','SEDE_REGIONALE') NOT NULL,
  area_id       BIGINT UNSIGNED NULL,
  status        ENUM('PENDING','APPROVATA','RIFIUTATA','ATTIVA','SOSPESA') NOT NULL DEFAULT 'PENDING',
  prezzo_euro   DECIMAL(18,2) NULL,
  canone_mensile_euro DECIMAL(18,2) NULL,
  pv_bonus_start DECIMAL(18,4) NULL,
  pv_bonus_mensile DECIMAL(18,4) NULL,
  note_admin    TEXT NULL,
  created_at    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (area_id) REFERENCES territory_areas(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
