ALTER TABLE accounts ADD COLUMN regione VARCHAR(40) NULL;
ALTER TABLE accounts ADD COLUMN ruolo VARCHAR(24) NOT NULL DEFAULT 'member';
ALTER TABLE accounts ADD COLUMN nodo_livello VARCHAR(16) NULL;
ALTER TABLE accounts ADD COLUMN genesys_rank VARCHAR(16) NULL;
ALTER TABLE accounts ADD COLUMN genesys_rank_dal VARCHAR(40) NULL;
ALTER TABLE accounts ADD COLUMN genesys_vol_personale INT NOT NULL DEFAULT 0;
ALTER TABLE accounts ADD COLUMN genesys_aziende_attive INT NOT NULL DEFAULT 0;
CREATE TABLE IF NOT EXISTS app_settings(k VARCHAR(64) PRIMARY KEY, v TEXT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
