ALTER TABLE accounts ADD COLUMN data_nascita VARCHAR(20) NULL;
ALTER TABLE accounts ADD COLUMN indirizzo VARCHAR(255) NULL;
ALTER TABLE accounts ADD COLUMN piva VARCHAR(16) NULL;
ALTER TABLE accounts ADD COLUMN pec VARCHAR(191) NULL;
ALTER TABLE accounts ADD COLUMN sdi VARCHAR(10) NULL;
ALTER TABLE accounts ADD COLUMN ateco VARCHAR(12) NULL;
ALTER TABLE accounts ADD COLUMN dipendenti INT NULL;
CREATE TABLE IF NOT EXISTS scadenze(id BIGINT AUTO_INCREMENT PRIMARY KEY,account_id BIGINT NOT NULL,titolo VARCHAR(160) NOT NULL,tipo VARCHAR(24) NOT NULL DEFAULT 'corso',data_scad VARCHAR(20) NOT NULL,stato VARCHAR(12) NOT NULL DEFAULT 'aperta',created_at VARCHAR(40) NOT NULL,INDEX(account_id),INDEX(data_scad)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
