ALTER TABLE accounts ADD COLUMN pwd_set_at VARCHAR(40) NULL;
CREATE TABLE IF NOT EXISTS pwd_resets(id BIGINT AUTO_INCREMENT PRIMARY KEY,account_id BIGINT NOT NULL,token VARCHAR(64) NOT NULL UNIQUE,expires_at VARCHAR(40) NOT NULL,used TINYINT NOT NULL DEFAULT 0,created_at VARCHAR(40) NOT NULL,INDEX(token)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
