-- HUB1 81plus.net, schema unico u173050672_81plusglobal. VARCHAR(191) per unique.
CREATE TABLE IF NOT EXISTS accounts(id BIGINT AUTO_INCREMENT PRIMARY KEY,sic VARCHAR(16) NOT NULL UNIQUE,email VARCHAR(191) NOT NULL UNIQUE,pass_hash VARCHAR(255) NOT NULL,tipo VARCHAR(16) NOT NULL DEFAULT 'persona',nome VARCHAR(120),cognome VARCHAR(120),ragione_sociale VARCHAR(191),tel VARCHAR(40),ref_by VARCHAR(16) NULL,codice_fiscale VARCHAR(16) NULL,data_nascita VARCHAR(20) NULL,indirizzo VARCHAR(255) NULL,piva VARCHAR(16) NULL,pec VARCHAR(191) NULL,sdi VARCHAR(10) NULL,ateco VARCHAR(12) NULL,dipendenti INT NULL,eth_address VARCHAR(42) NULL,avatar_url VARCHAR(255) NULL,kyc_level INT NOT NULL DEFAULT 0,status VARCHAR(16) NOT NULL DEFAULT 'attivo',email_verified TINYINT NOT NULL DEFAULT 0,set_token VARCHAR(64) NULL,pwd_set_at VARCHAR(40) NULL,created_at VARCHAR(40) NOT NULL,INDEX(ref_by)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS sessions(id BIGINT AUTO_INCREMENT PRIMARY KEY,account_id BIGINT NOT NULL,token VARCHAR(64) NOT NULL UNIQUE,created_at VARCHAR(40) NOT NULL,expires_at VARCHAR(40) NOT NULL,INDEX(account_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS pv_ledger(id BIGINT AUTO_INCREMENT PRIMARY KEY,account_id BIGINT NOT NULL,delta INT NOT NULL,reason VARCHAR(60) NOT NULL,ref VARCHAR(60) NULL,created_at VARCHAR(40) NOT NULL,INDEX(account_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS pv_transfers(id BIGINT AUTO_INCREMENT PRIMARY KEY,from_account BIGINT NOT NULL,to_sic VARCHAR(16) NOT NULL,amount INT NOT NULL,created_at VARCHAR(40) NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS leads(id BIGINT AUTO_INCREMENT PRIMARY KEY,email VARCHAR(191) NOT NULL,nome VARCHAR(120),source VARCHAR(40),sic VARCHAR(16) NULL,owner_sic VARCHAR(16) NULL,stage VARCHAR(16) NOT NULL DEFAULT 'nuovo',consenso_mkt VARCHAR(8) NULL,created_at VARCHAR(40) NOT NULL,INDEX(email),INDEX(owner_sic)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS audit_runs(id BIGINT AUTO_INCREMENT PRIMARY KEY,account_id BIGINT NULL,lead_id BIGINT NULL,score INT,gaps TEXT,payload TEXT,created_at VARCHAR(40) NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS entitlements(id BIGINT AUTO_INCREMENT PRIMARY KEY,ent_key VARCHAR(64) NOT NULL UNIQUE,account_id BIGINT NOT NULL,product VARCHAR(40) NOT NULL,status VARCHAR(16) NOT NULL DEFAULT 'inactive',provider VARCHAR(40),provider_ref VARCHAR(191),valid_until VARCHAR(40)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS payments(id BIGINT AUTO_INCREMENT PRIMARY KEY,account_id BIGINT NOT NULL,provider VARCHAR(40) NOT NULL,provider_ref VARCHAR(191) NOT NULL UNIQUE,amount_cents INT NOT NULL,currency VARCHAR(8) NOT NULL,status VARCHAR(24),raw MEDIUMTEXT,created_at VARCHAR(40) NOT NULL,INDEX(account_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS network_nodes(account_id BIGINT PRIMARY KEY,parent_sic VARCHAR(16) NULL,rank INT NOT NULL DEFAULT 0,qualified TINYINT NOT NULL DEFAULT 0,vol_personal INT NOT NULL DEFAULT 0,vol_group INT NOT NULL DEFAULT 0,updated_at VARCHAR(40),INDEX(parent_sic)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS rate_limits(id BIGINT AUTO_INCREMENT PRIMARY KEY,k VARCHAR(120) NOT NULL,ts BIGINT NOT NULL,INDEX(k),INDEX(ts)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS events(id BIGINT AUTO_INCREMENT PRIMARY KEY,account_id BIGINT NULL,type VARCHAR(40) NOT NULL,data TEXT,created_at VARCHAR(40) NOT NULL,INDEX(type)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS promo_early_bird(id BIGINT AUTO_INCREMENT PRIMARY KEY,cycle VARCHAR(7) NOT NULL,account_id BIGINT NOT NULL,created_at VARCHAR(40) NOT NULL,UNIQUE KEY uq_cycle_acc(cycle,account_id),INDEX(cycle)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sales(id BIGINT AUTO_INCREMENT PRIMARY KEY,seller_id BIGINT NOT NULL,amount_cents INT NOT NULL,product VARCHAR(40),created_at VARCHAR(40) NOT NULL,INDEX(seller_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS newsletter(id BIGINT AUTO_INCREMENT PRIMARY KEY,email VARCHAR(191) NOT NULL UNIQUE,nome VARCHAR(120),fonte VARCHAR(40),consenso VARCHAR(120),stato VARCHAR(16) NOT NULL DEFAULT 'ATTIVO',created_at VARCHAR(40) NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS welcome_queue(id BIGINT AUTO_INCREMENT PRIMARY KEY,email VARCHAR(191) NOT NULL UNIQUE,nome VARCHAR(120),step INT NOT NULL DEFAULT 0,next_at VARCHAR(40) NOT NULL,stato VARCHAR(16) NOT NULL DEFAULT 'ATTIVO',serie VARCHAR(16) NOT NULL DEFAULT 'nurture',unsub_token VARCHAR(64) NOT NULL,created_at VARCHAR(40) NOT NULL,INDEX(next_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS wallets(id BIGINT AUTO_INCREMENT PRIMARY KEY,account_id BIGINT NOT NULL,tipo VARCHAR(12) NOT NULL,wallet_code VARCHAR(32) NOT NULL UNIQUE,created_at VARCHAR(40) NOT NULL,UNIQUE KEY uq_acc_tipo(account_id,tipo)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS wallet_nonces(id BIGINT AUTO_INCREMENT PRIMARY KEY,nonce VARCHAR(64) NOT NULL UNIQUE,address VARCHAR(42) NULL,created_at VARCHAR(40) NOT NULL,used TINYINT NOT NULL DEFAULT 0,INDEX(nonce)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS kyc(id BIGINT AUTO_INCREMENT PRIMARY KEY,account_id BIGINT NOT NULL UNIQUE,livello INT NOT NULL DEFAULT 0,stato VARCHAR(16) NOT NULL DEFAULT 'assente',nome VARCHAR(120),cognome VARCHAR(120),codice_fiscale VARCHAR(16),data_nascita VARCHAR(20),doc_tipo VARCHAR(20),doc_numero VARCHAR(40),provider VARCHAR(40),provider_ref VARCHAR(120),note VARCHAR(255),updated_at VARCHAR(40)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS wallet_chains(id BIGINT AUTO_INCREMENT PRIMARY KEY,account_id BIGINT NOT NULL,chain VARCHAR(12) NOT NULL,address VARCHAR(64) NOT NULL,verified TINYINT NOT NULL DEFAULT 0,created_at VARCHAR(40) NOT NULL,UNIQUE KEY uq_acc_chain(account_id,chain)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS swap_intents(id BIGINT AUTO_INCREMENT PRIMARY KEY,account_id BIGINT NOT NULL,da VARCHAR(8) NOT NULL,a VARCHAR(8) NOT NULL,importo_da DECIMAL(24,8) NOT NULL,quote_a DECIMAL(24,8) NOT NULL,rate DECIMAL(24,8) NOT NULL,stato VARCHAR(16) NOT NULL DEFAULT 'bozza',provider VARCHAR(40) NULL,provider_ref VARCHAR(120) NULL,created_at VARCHAR(40) NOT NULL,INDEX(account_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS scadenze(id BIGINT AUTO_INCREMENT PRIMARY KEY,account_id BIGINT NOT NULL,titolo VARCHAR(160) NOT NULL,tipo VARCHAR(24) NOT NULL DEFAULT 'corso',data_scad VARCHAR(20) NOT NULL,stato VARCHAR(12) NOT NULL DEFAULT 'aperta',created_at VARCHAR(40) NOT NULL,INDEX(account_id),INDEX(data_scad)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS doc_unlocks(id BIGINT AUTO_INCREMENT PRIMARY KEY,account_id BIGINT NOT NULL,doc_id VARCHAR(20) NOT NULL,via VARCHAR(16) NOT NULL DEFAULT 'pv',created_at VARCHAR(40) NOT NULL,UNIQUE KEY uq_acc_doc(account_id,doc_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS badges(id BIGINT AUTO_INCREMENT PRIMARY KEY,account_id BIGINT NOT NULL,badge_id VARCHAR(24) NOT NULL,created_at VARCHAR(40) NOT NULL,UNIQUE KEY uq_acc_badge(account_id,badge_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS pwd_resets(id BIGINT AUTO_INCREMENT PRIMARY KEY,account_id BIGINT NOT NULL,token VARCHAR(64) NOT NULL UNIQUE,expires_at VARCHAR(40) NOT NULL,used TINYINT NOT NULL DEFAULT 0,created_at VARCHAR(40) NOT NULL,INDEX(token)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ai_decisions(id BIGINT AUTO_INCREMENT PRIMARY KEY,account_id BIGINT NOT NULL,evento VARCHAR(40) NOT NULL,situazione TEXT,problema TEXT,azione VARCHAR(255),reward_pv INT NOT NULL DEFAULT 0,link VARCHAR(255),moduli TEXT,score INT NOT NULL DEFAULT 0,created_at VARCHAR(40) NOT NULL,INDEX(account_id),INDEX(created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS missions(id BIGINT AUTO_INCREMENT PRIMARY KEY,account_id BIGINT NOT NULL,tipo VARCHAR(40) NOT NULL,titolo VARCHAR(255),reward_pv INT NOT NULL DEFAULT 0,stato VARCHAR(16) NOT NULL DEFAULT 'attiva',scade_il VARCHAR(40) NULL,created_at VARCHAR(40) NOT NULL,completata_il VARCHAR(40) NULL,INDEX(account_id),INDEX(stato)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS blog_posts(id BIGINT AUTO_INCREMENT PRIMARY KEY,slug VARCHAR(120) NOT NULL UNIQUE,titolo VARCHAR(200) NOT NULL,estratto VARCHAR(400),corpo TEXT,data VARCHAR(20) NOT NULL,categoria VARCHAR(30),fonte_nome VARCHAR(120),fonte_url VARCHAR(500),fonte_hash VARCHAR(64),origine VARCHAR(10) NOT NULL DEFAULT 'auto',stato VARCHAR(12) NOT NULL DEFAULT 'pubblicato',created_at VARCHAR(40) NOT NULL,INDEX(fonte_hash),INDEX(stato)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- v12 email comportamentali
CREATE TABLE IF NOT EXISTS trigger_sent (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(190) NOT NULL,
  trig VARCHAR(60) NOT NULL,
  created_at VARCHAR(40),
  UNIQUE KEY uq_email_trig (email, trig)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- v13 sicurezza, 2FA email
-- ALTER TABLE accounts ADD COLUMN twofa VARCHAR(10) DEFAULT 'off';
CREATE TABLE IF NOT EXISTS twofa_codes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  account_id INT NOT NULL,
  code_hash VARCHAR(190) NOT NULL,
  scopo VARCHAR(20) DEFAULT 'login',
  expires_at VARCHAR(40),
  used TINYINT DEFAULT 0,
  created_at VARCHAR(40),
  KEY idx_acc (account_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
