<?php
// Da chiamare ogni ora dal cron di Hostinger: curl "https://tuodominio/api/cron.php?key=CRON_SECRET"
require_once __DIR__.'/../src/db.php'; require_once __DIR__.'/../src/welcome_flow.php'; require_once __DIR__.'/../src/blog_bot.php'; require_once __DIR__.'/../src/trigger_mail.php'; require_once __DIR__.'/../src/seo81.php'; require_once __DIR__.'/../src/telegram81.php'; require_once __DIR__.'/../src/brevo81.php'; require_once __DIR__.'/../src/ai81.php'; require_once __DIR__.'/../src/scadenze81.php'; require_once __DIR__.'/../src/wallet81.php';
require_once __DIR__.'/../src/sequenze.php'; require_once __DIR__.'/../src/promo81w.php';
require_once __DIR__.'/../src/trigger_mail.php'; require_once __DIR__.'/../src/seo81.php'; require_once __DIR__.'/../src/telegram81.php'; require_once __DIR__.'/../src/brevo81.php'; require_once __DIR__.'/../src/ai81.php'; require_once __DIR__.'/../src/scadenze81.php'; require_once __DIR__.'/../src/wallet81.php'; require_once __DIR__.'/../src/promo81w.php';
function campiProfilo($a){ $tipo=$a['tipo']??'persona'; if($tipo==='azienda'){ $req=['ragione_sociale','piva','tel','pec','ateco']; } else { $req=['nome','cognome','codice_fiscale','tel','data_nascita','indirizzo']; } $fatti=0; foreach($req as $k){ if(trim((string)($a[$k]??''))!=='') $fatti++; } return [$req,$fatti]; }
function profiloCompleto($a){ list($req,$fatti)=campiProfilo($a); return $fatti===count($req); }
require_once __DIR__.'/../src/orchestrator.php'; require_once __DIR__.'/../src/genesys_rank.php';
$key=getenv('CRON_SECRET')?:''; if(!$key||($_GET['key']??'')!==$key){ http_response_code(403); exit('no'); }
$n=processaWelcome(80); $r=orchestratorSweepInattivi(db(),40); $blog=bbGiro(false); $trig=triggerMailSweep(db(),60); $seo=seoRigenera(); $tg=tgGiro(db()); $brevo=brevoSyncNuovi(db()); $ai=aiGiro(db()); $scad=scAvvisi(db()); $saldoAvv=wAvvisiSaldo(db()); $promoTg=promoTelegram(db()); $seqC=seqSweep(db()); $gRank=gVerificaMantenimento(db(),200); j(['ok'=>true,'inviate'=>$n,'riattivazioni'=>$r,'blog'=>$blog,'comportamentali'=>$trig,'seo'=>$seo,'telegram'=>$tg,'brevo'=>$brevo,'ai'=>$ai,'scadenze_avvisate'=>$scad,'avvisi_saldo'=>$saldoAvv,'promo_telegram'=>$promoTg,'sequenza_conversione'=>$seqC,'genesys_mantenimento'=>$gRank]);
