-- MYSQL_DELTA_NETWORKER_SCOUT_PLP_PIANI.sql

SET NAMES utf8mb4;

-- SDK+ / SDP+ PASS
CREATE TABLE IF NOT EXISTS network_passes (
  id            BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id       BIGINT UNSIGNED NOT NULL,
  tipo          ENUM('SDK+','SDP+','SDK_ROYAL','SDP_ROYAL') NOT NULL,
  livello       VARCHAR(30) NOT NULL COMMENT 'IGNITE, RISE, DRIVE, SCALE, PEAK, SUMMIT, LEGACY, CROWN ecc.',
  prezzo_pv     DECIMAL(18,4) NOT NULL,
  status        ENUM('ACTIVE','EXPIRED','CANCELLED') NOT NULL DEFAULT 'ACTIVE',
  attivo_dal    DATE NOT NULL,
  scade_il      DATE NULL,
  created_at    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  INDEX idx_user_tipo (user_id, tipo)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- PIANO COMPENSI
CREATE TABLE IF NOT EXISTS piano_compensi_config (
  id            BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  versione      VARCHAR(20) NOT NULL,
  dati          JSON NOT NULL COMMENT 'tutte le regole compensi in JSON',
  attivo        TINYINT(1) NOT NULL DEFAULT 1,
  pubblicato_il DATE NOT NULL,
  note          TEXT NULL,
  created_at    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- COMPENSI MATURATI
CREATE TABLE IF NOT EXISTS compensi_maturati (
  id            BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id       BIGINT UNSIGNED NOT NULL,
  mese          CHAR(7) NOT NULL COMMENT 'YYYY-MM',
  tipo          ENUM('PROVVIGIONE_DIRETTA','OVERRIDE','CLUB_BONUS','FRANCHISE_BONUS','ALTRO') NOT NULL,
  importo       DECIMAL(18,4) NOT NULL,
  valuta        ENUM('PV','EURO') NOT NULL DEFAULT 'PV',
  riferimento_vendita BIGINT UNSIGNED NULL,
  status        ENUM('MATURATO','VALIDATO','PAGATO','BLOCCATO') NOT NULL DEFAULT 'MATURATO',
  note          VARCHAR(255) NULL,
  created_at    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  INDEX idx_user_mese (user_id, mese)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- REGOLA GIORNO 20
CREATE TABLE IF NOT EXISTS regola_giorno20_check (
  id            BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id       BIGINT UNSIGNED NOT NULL,
  mese          CHAR(7) NOT NULL COMMENT 'YYYY-MM',
  membership_attiva TINYINT(1) NOT NULL DEFAULT 0,
  pass_attivo   TINYINT(1) NOT NULL DEFAULT 0,
  no_blocco_admin TINYINT(1) NOT NULL DEFAULT 1,
  kyc_ok        TINYINT(1) NOT NULL DEFAULT 0,
  iban_wallet_ok TINYINT(1) NOT NULL DEFAULT 0,
  attivo_giorno20 TINYINT(1) NOT NULL DEFAULT 0,
  compenso_erogato TINYINT(1) NOT NULL DEFAULT 0,
  compenso_tesoreria TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'va a Tesoreria Nazionale Green81+ se inattivo',
  checked_at    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uk_user_mese (user_id, mese),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- MATERIALI NETWORKER
CREATE TABLE IF NOT EXISTS materiali_networker (
  id            BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  tipo          ENUM('SOCIAL','WEBINAR','SCRIPT','PDF','VIDEO','ALTRO') NOT NULL,
  titolo        VARCHAR(255) NOT NULL,
  descrizione   TEXT NULL,
  file_path     VARCHAR(255) NULL,
  link_esterno  VARCHAR(255) NULL,
  livello_minimo ENUM('NETWORKER81','ELITE81','ADMIN81') NOT NULL DEFAULT 'NETWORKER81',
  attivo        TINYINT(1) NOT NULL DEFAULT 1,
  created_at    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
